services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\AdministrationBundle\:
        exclude:
            - '../src/DependencyInjection/'
        resource: '../src/'

    Shopsys\AdministrationBundle\Twig\Runtime\DomainIconRuntime:
        arguments:
            - '%kernel.project_dir%'
        tags: ['twig.runtime']
